Repository Step3-kakao-tech-campus/Team7_FE, pull requests merged in 2023-10, with the labels that each got.

#44 feat: Logo 컴포넌트 구현 및 스토리 작성
  src/components/common/Logo/index.stories.tsx
  src/components/common/Logo/index.tsx
  src/components/common/Logo/style.ts
Labels: 💄UI, 📍 개발

#47 feat: 각 페이지 별로 레이아웃 지정 가능한 유틸 함수 및 기능 구현
  package.json
  src/components/common/Logo/style.ts
  src/components/layout/EmptyLayou.tsx
  src/components/layout/FullHeightLayout.tsx
  src/pages/_app.tsx
  src/pages/auth/verify.tsx
  src/utils/layout.tsx
  yarn.lock
Labels: 💄UI, 📍 개발

#50 [회원가입 페이지] 이메일 인증 구현
  package.json
  src/api/auth/index.ts
  src/api/auth/types.ts
  src/api/hello.ts
  src/components/auth/register/verify/ByEmail/index.tsx
  src/components/auth/register/verify/ByEmail/style.ts
  src/components/auth/register/verify/CodeCheck/index.tsx
  src/components/auth/register/verify/CodeCheck/style.ts
  src/components/auth/register/verify/Verify.tsx
  src/components/auth/register/verify/VerifyModal/index.tsx
  src/components/auth/register/verify/VerifyModal/style.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/components/common/Spinner/index.tsx
  src/constants/regex.ts
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/register.ts
  src/mocks/server.ts
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/auth/register.tsx
  src/pages/auth/verify.tsx
  src/styles/emotion/index.tsx
  yarn.lock
Labels: 💄UI, 📍 개발

#48 feat: 메인페이지
  package.json
  public/assets/icons/ic_chevronDownBlack.svg
  public/assets/icons/ic_profile.svg
  src/api/roadmap/index.ts
  src/api/roadmap/type.ts
  src/api/til/index.ts
  src/api/til/type.ts
  src/components/common/CustomSuspense/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/GNB/style.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/components/main/CategorySection/index.tsx
  src/components/main/CategorySection/style.ts
  src/components/main/Collapsible/index.stories.tsx
  src/components/main/Collapsible/index.tsx
  src/components/main/Collapsible/style.ts
  src/components/main/History/index.tsx
  src/components/main/History/style.ts
  src/components/main/SearchBar/index.tsx
  src/components/main/SearchBar/style.ts
  src/components/main/TIL/index.tsx
  src/components/main/TIL/style.ts
  src/components/main/TILSection/index.tsx
  src/components/main/TILSection/style.ts
  src/constants/links.ts
  src/hooks/common/useInterSectionObserver.ts
  src/hooks/common/useParamsToUrl.ts
  src/hooks/queries/roadmap.ts
  src/hooks/queries/til.ts
  src/hooks/queries/user.ts
  src/mocks/fixtures/roadmap.ts
  src/mocks/fixtures/til.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/roadmap.ts
  src/mocks/handlers/til.ts
  src/pages/index.tsx
  src/pages/roadmaps/index.tsx
  src/styles/globals.css
  yarn.lock
Labels: 💄UI, 📍 개발

#55 feat: [회원가입 페이지] 정보 입력
  src/api/auth/index.ts
  src/api/auth/type.ts
  src/api/auth/types.ts
  src/components/auth/register/Register.tsx
  src/components/auth/register/RegisterModal/index.tsx
  src/components/auth/register/RegisterModal/style.ts
  src/components/auth/verify/ByEmail/index.tsx
  src/components/auth/verify/ByEmail/style.ts
  src/components/auth/verify/CodeCheck/index.tsx
  src/components/auth/verify/CodeCheck/style.ts
  src/components/auth/verify/Verify.tsx
  src/components/auth/verify/VerifyModal/index.tsx
  src/components/auth/verify/VerifyModal/style.ts
  src/constants/links.ts
  src/constants/regex.ts
  src/mocks/fixtures/auth.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/register.ts
  src/pages/auth/login.tsx
  src/pages/auth/register.tsx
  src/pages/auth/verify.tsx
Labels: 💄UI, 📍 개발

#59 feat: 로그인 페이지 및 기능 구현
  src/api/auth/index.ts
  src/api/auth/type.ts
  src/components/auth/login/index.tsx
  src/components/auth/register/Register.tsx
  src/mocks/fixtures/auth.ts
  src/mocks/handlers/auth.ts
  src/pages/auth/login.tsx
Labels: 💄UI, 📍 개발

#69 feat: 토큰을 통한 로그인 상태 관리
  package.json
  src/api/auth/type.ts
  src/components/auth/login/index.tsx
  src/components/auth/states/accessTokenAtoms.ts
  src/mocks/fixtures/auth.ts
  src/pages/_app.tsx
  src/utils/accessToken.ts
  yarn.lock
Labels: 💄UI, 📍 개발

#75 feat: 비밀번호 변경 레이아웃 및 기능
  src/api/auth/index.ts
  src/api/auth/type.ts
  src/components/auth/AuthModal/index.tsx
  src/components/auth/AuthModal/style.ts
  src/components/auth/change-password/index.tsx
  src/components/auth/register/index.tsx
  src/components/auth/verify/ByEmail/index.tsx
  src/components/auth/verify/CodeCheck/index.tsx
  src/constants/links.ts
  src/mocks/fixtures/auth.ts
  src/mocks/handlers/auth.ts
  src/pages/auth/change-password/index.tsx
  src/pages/auth/change-password/verify.tsx
  src/pages/auth/login.tsx
  src/pages/auth/register/index.tsx
  src/pages/auth/register/verify.tsx
Labels: 💄UI, 📍 개발

#78 [메인 페이지] 알림 UI
  next.config.js
  public/assets/icons/ic_smile.svg
  public/assets/icons/ic_unAlarm.svg
  public/assets/icons/ic_unlock.svg
  src/api/hooks/user.ts
  src/api/type.ts
  src/api/user/index.ts
  src/api/user/type.ts
  src/api/user/types.ts
  src/components/TILWrite/Comments/Comment/index.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/Avatar/style.ts
  src/components/common/Card/index.tsx
  src/components/common/GNB/Alarm/index.tsx
  src/components/common/GNB/Alarm/style.ts
  src/components/common/GNB/Personal/index.tsx
  src/components/common/GNB/RoadMap/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/GNB/style.ts
  src/components/main/TIL/index.tsx
  src/constants/links.ts
  src/hooks/useAuth.ts
  src/hooks/useModalState.ts
  src/mocks/fixtures/user.ts
  src/mocks/handlers/user.ts
  src/pages/TILWrite/index.tsx
  src/pages/index.tsx
  src/pages/intro/index.tsx
  src/pages/mypage/index.tsx
  src/styles/emotion/index.tsx
  src/utils/accessToken.ts
  src/utils/getTilWriteUrl.ts
Labels: 💄UI, 📍 개발

#77 feat: auth 확인 레이아웃 (HOC) 구현
  src/components/auth/utils/AuthRequired.tsx
  src/components/layout/EmptyLayout.tsx
  src/pages/index.tsx
  src/utils/layout.tsx
Labels: 💄UI, 📍 개발

#81 fix: 모달 커스텀 훅 경로 에러 해결
  src/components/auth/change-password/index.tsx
  src/components/auth/register/index.tsx
  src/components/auth/verify/ByEmail/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Modal/index.stories.tsx
  src/pages/index.tsx
Labels: 🐜 버그

#87 refactor: 4주차 코드 리뷰 반영
  src/components/common/IconButton/index.tsx
  src/components/common/Portal/index.tsx
  src/components/common/Select/index.tsx
  src/components/common/Select/style.ts
Labels: 🛠 리팩터링

#92 feat: HeaderLayout 구현
  src/components/layout/EmptyLayout.tsx
  src/components/layout/FullHeightLayout.tsx
  src/components/layout/HeaderLayout.tsx
  src/pages/index.tsx
  src/pages/roadmap/index.tsx
Labels: 💄UI, 📍 개발

#93 feat: 다른 사람 TIL 보는 페이지 구현
  public/assets/icons/ic_comment.svg
  public/assets/icons/ic_commentBlack.svg
  public/assets/icons/ic_peopleTILEmpty.svg
  public/assets/icons/ic_stair.svg
  public/assets/icons/ic_think.svg
  public/assets/icons/ic_triangleAlert.svg
  src/components/common/Fallback/index.tsx
  src/components/common/Fallback/style.ts
  src/components/common/GNB/index.tsx
  src/components/roadmap/PeopleTIL/FeatureInfoSection/index.tsx
  src/components/roadmap/PeopleTIL/FeatureInfoSection/style.ts
  src/components/roadmap/PeopleTIL/PeopleTILSection/index.tsx
  src/components/roadmap/PeopleTIL/PeopleTILSection/style.ts
  src/components/roadmap/PeopleTIL/TIL/index.tsx
  src/components/roadmap/PeopleTIL/TIL/style.ts
  src/pages/TILWrite/roadmap/[roadmapId]/step/[stepId]/til/[tilId].tsx
  src/pages/roadmap/[roadmapId]/step/[stepId].tsx
Labels: 💄UI, 📍 개발

#95 feat: 다른사람 TIL 보는 페이지 API 연결
  src/api/hooks/til.ts
  src/api/til/index.ts
  src/api/til/type.ts
  src/components/TILWrite/Header/index.tsx
  src/components/roadmap/PeopleTIL/PeopleTILSection/index.tsx
  src/components/roadmap/PeopleTIL/TIL/index.tsx
  src/mocks/fixtures/til.ts
  src/mocks/handlers/til.ts
  src/pages/roadmap/[roadmapId]/step/[stepId].tsx
Labels: 📍 개발

#97 feat: 로드맵 생성 <기본 정보 입력> 구현
  public/assets/icons/ic_step.svg
  src/components/Roadmap/RoadmapCreate/Header/index.tsx
  src/components/Roadmap/RoadmapCreate/Header/style.ts
  src/components/Roadmap/RoadmapCreate/Info/index.tsx
  src/components/Roadmap/RoadmapCreate/Info/style.ts
  src/components/Roadmap/RoadmapCreate/Step/StepSection/index.tsx
  src/components/Roadmap/RoadmapCreate/Step/StepSection/style.ts
  src/components/Roadmap/RoadmapCreate/Step/index.tsx
  src/components/Roadmap/RoadmapCreate/Step/style.ts
  src/components/common/Calendar/index.tsx
  src/components/common/Calendar/style.ts
  src/components/common/TextArea/index.tsx
  src/components/common/TextArea/style.ts
  src/constants/links.ts
  src/hooks/useRoedmapCreate.ts
  src/pages/roadmap/create/index.tsx
  src/pages/roadmap/index.tsx
Labels: 💄UI, 📍 개발

#98 feat: 에러 바운더리 도입
  package.json
  public/assets/icons/404.svg
  public/assets/icons/500.svg
  src/api/hooks/roadmap.ts
  src/components/common/ConditionalRender/index.tsx
  src/components/common/Fallback/index.tsx
  src/components/common/FallbackErrorBoundary/index.tsx
  src/components/common/GNB/Personal/index.tsx
  src/components/common/GlobalErrorBoundary/index.tsx
  src/components/common/GlobalErrorBoundary/style.ts
  src/components/common/Modal/style.ts
  src/components/common/Toast/index.tsx
  src/components/common/Toast/provider/index.tsx
  src/components/common/Toast/provider/style.ts
  src/components/common/Toast/style.ts
  src/components/main/History/index.tsx
  src/components/main/History/style.ts
  src/components/main/TILSection/index.tsx
  src/components/main/TILSection/style.ts
  src/components/roadmap/PeopleTIL/PeopleTILSection/index.tsx
  src/hooks/useApiError.ts
  src/mocks/handlers/til.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/roadmap/[roadmapId]/step/[stepId].tsx
  src/styles/emotion/index.tsx
  yarn.lock
Labels: 💄UI, 📍 개발

#104 feat: 로드맵 생성 <STEP 생성 기능>
  src/components/Roadmap/RoadmapCreate/InfoSection/index.tsx
  src/components/Roadmap/RoadmapCreate/InfoSection/style.ts
  src/components/Roadmap/RoadmapCreate/Step/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepModal/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepModal/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepSection/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepSection/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/style.ts
  src/components/common/Calendar/index.tsx
  src/components/common/Calendar/style.ts
  src/components/common/Input/index.tsx
  src/hooks/useRoedmapCreate.ts
  src/pages/roadmap/create/index.tsx
Labels: 💄UI, 📍 개발

#100 feat: TIL VIEW 페이지
  src/components/TILView/Ckeditor/defaultData.ts
  src/components/TILView/Ckeditor/index.tsx
  src/components/TILView/Ckeditor/plugin.ts
  src/components/TILView/Comments/Comment/index.tsx
  src/components/TILView/Comments/CommentPatchModal/index.tsx
  src/components/TILView/Comments/Header/index.tsx
  src/components/TILView/Comments/TextAreaSection/index.tsx
  src/components/TILView/Comments/index.tsx
  src/components/TILView/Footer/index.tsx
  src/components/TILView/Header/index.tsx
  src/components/TILWrite/Ckeditor/style.ts
  src/components/TILWrite/Comments/style.ts
  src/components/roadmap/PeopleTIL/TIL/index.tsx
  src/components/roadmap/PeopleTIL/TIL/style.ts
  src/constants/links.ts
  src/pages/TILView/roadmap/[roadmapId]/step/[stepId]/til/[tilId].tsx
  src/pages/TILWrite/roadmap/[roadmapId]/step/[stepId]/til/[tilId].tsx
Labels: 💄UI, 📍 개발

#112 feat: 로드맵 생성 <참고 자료 추가> 기능 구현
  public/assets/icons/ic_chevronUpBlack.svg
  public/assets/icons/ic_edit.svg
  public/assets/icons/ic_noLink.svg
  public/assets/icons/ic_trash.svg
  public/assets/icons/ic_web.svg
  public/assets/icons/ic_youtube.svg
  src/components/Roadmap/RoadmapCreate/InfoSection/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/ReferenceList/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/ReferenceList/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/WebBox/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/WebModal/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/WebModal/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/YoutubeBox/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/YoutubeBox/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/YoutubeModal/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/YoutubeModal/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepModal/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepSection/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/index.tsx
  src/components/Roadmap/RoadmapCreate/states/roadmapCreateAtoms.ts
  src/components/common/Input/index.tsx
  src/hooks/useRoedmapCreate.ts
  src/hooks/useStepInfo.ts
  src/pages/roadmap/create/index.tsx
Labels: 💄UI, 📍 개발

#117 feat: 로드맵 생성 참고자료, STEP
  src/api/hooks/roadmap.ts
  src/api/roadmap/index.ts
  src/api/roadmap/type.ts
  src/components/Roadmap/RoadmapCreate/Header/index.tsx
  src/components/Roadmap/RoadmapCreate/Header/style.ts
  src/components/Roadmap/RoadmapCreate/InfoSection/index.tsx
  src/components/Roadmap/RoadmapCreate/InfoSection/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepDeleteModal/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/ReferenceList/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/WebBox/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/WebModal/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/YoutubeBox/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepModal/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/index.tsx
  src/components/Roadmap/RoadmapCreate/states/roadmapCreateAtoms.ts
  src/components/common/Calendar/index.tsx
  src/constants/regex.ts
  src/hooks/useRoadmapCreate.ts
  src/hooks/useStepInfo.ts
  src/mocks/fixtures/roadmap.ts
  src/mocks/handlers/roadmap.ts
  src/pages/roadmap/create/index.tsx
Labels: 💄UI, 📍 개발, 🛠 리팩터링

#140 feat: 로드맵 목록 1차 구현
  .gitignore
  next.config.js
  package-lock.json
  package.json
  src/api/hooks/roadmap.ts
  src/api/roadmap/index.ts
  src/api/roadmap/type.ts
  src/components/Roadmap/GroupCard/index.tsx
  src/components/Roadmap/GroupCard/style.ts
  src/components/Roadmap/MyRoadmap/index.tsx
  src/components/Roadmap/MyRoadmap/style.ts
  src/components/Roadmap/RecruitRoadmap/index.tsx
  src/components/Roadmap/RecruitRoadmap/style.ts
  src/components/Roadmap/TilyCard/index.tsx
  src/components/Roadmap/TilyCard/style.ts
  src/components/common/GNB/desktop/Personal/index.tsx
  src/components/common/GNB/desktop/RoadMap/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/GNB/mobile/MobilePersonal/index.tsx
  src/components/main/CategorySection/index.tsx
  src/components/main/TILSection/index.tsx
  src/components/main/mobile/SideBar/index.tsx
  src/hooks/useQueryParam.ts
  src/hooks/useRoadmapCreate.ts
  src/mocks/fixtures/roadmap.ts
  src/mocks/handlers/roadmap.ts
  src/pages/roadmap/index.tsx
  yarn.lock
Labels: 💄UI, 📍 개발

#150 feat: 로드맵 목록 페이지 (모바일 반응형) + 로드맵 생성 모바일 반응형
  public/assets/icons/ic_mountain.svg
  src/api/hooks/roadmap.ts
  src/api/roadmap/type.ts
  src/api/type.ts
  src/components/Roadmap/GroupCard/style.ts
  src/components/Roadmap/MyRoadmap/MyRoadmapList/index.tsx
  src/components/Roadmap/MyRoadmap/MyRoadmapList/style.ts
  src/components/Roadmap/MyRoadmap/index.tsx
  src/components/Roadmap/MyRoadmap/style.ts
  src/components/Roadmap/RecruitRoadmap/RecruitRoadmapList/index.tsx
  src/components/Roadmap/RecruitRoadmap/RecruitRoadmapList/style.ts
  src/components/Roadmap/RecruitRoadmap/index.tsx
  src/components/Roadmap/RecruitRoadmap/style.ts
  src/components/Roadmap/RoadmapCodeModal/index.tsx
  src/components/Roadmap/RoadmapCodeModal/style.ts
  src/components/Roadmap/RoadmapCreate/InfoSection/index.tsx
  src/components/Roadmap/RoadmapCreate/InfoSection/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/ReferenceList/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/ReferenceList/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/YoutubeBox/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/YoutubeModal/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/StepBox/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepList/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/StepModal/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/StepModal/style.ts
  src/components/Roadmap/RoadmapCreate/StepSection/index.tsx
  src/components/Roadmap/RoadmapCreate/StepSection/style.ts
  src/components/common/Calendar/index.tsx
  src/components/common/Modal/style.ts
  src/hooks/useParamsToUrl.ts
  src/pages/roadmap/create/index.tsx
  src/pages/roadmap/index.tsx
Labels: 💄UI, 📍 개발, 🛠 리팩터링
